import { Button, StyleSheet } from "react-native";

export const stylesContrat = StyleSheet.create({
//----------------TELA PRINCIPAL-------------------- 
    Cards:{
        flexDirection:'row',
        margin:'7%',
        marginRight:'15%',
        marginTop:'13%',
        gap: 25,
    },
    CardBuscar:{
        backgroundColor:'#DEDEDE',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 10,
        marginLeft:'-2%',
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 5,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
  
    },
    BuscarM:{
        alignItems:'center',
    },
    BuscarTxt:{
        fontSize: 17,
        fontWeight: '400',
        justifyContent:'center',
    },
    ImagTruck1:{
        marginLeft:'10%',
        marginTop:'5%',
    },
    CardDivulgar:{
        backgroundColor:'#DEDEDE',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 5,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
  
    },
    Divulgar:{
        alignItems:'center',
    },
    DivulgarTxt:{
        fontSize: 17,
        fontWeight: '400',
    },
    ImagTruck2:{
        marginLeft:'10%',
        marginTop:'5%',
    },



//------------------------------SOLICITAR SERVIÇO---------------------------------------   
txtservico: {
    flex: 1,
},
Txtservico_1: {
    marginLeft: '14%',
    color: '#10C18D',
    marginTop: '10%',
    fontSize: 20,
    fontWeight: '600',
},
solcimputes: {
    flex: 1,
    alignItems:'center',
    justifyContent: 'center',
    width:'70%',
    height:'80%',
    marginLeft: '15%',
},
inputservico: {
    backgroundColor:'#E1E1E1',
    width:'100%',
    marginBottom: 15,
    color: '#222',
    fontSize: 15,
    borderRadius: 13,
    padding: 10,
    marginTop: '3%',
},
txtservico2: {
    flex: 1,
    marginTop: '10%',
},
Txtservico_2: {
    marginLeft: '14%',
    color: '#10C18D',
    fontSize: 20,
    fontWeight: '600',
},
Txtservico_3: {
    color: '#113164',
    marginTop: '3%',
    marginLeft: '17%',
    fontSize: 17,
    fontWeight: '600',
},
solcimputes2: {
    flex: 1,
    alignItems:'center',
    justifyContent: 'center',
    width:'70%',
    height:'80%',
    marginLeft: '15%',
},
inputservico2: {
    backgroundColor:'#E1E1E1',
    width:'100%',
    marginBottom: 15,
    color: '#222',
    fontSize: 15,
    borderRadius: 13,
    padding: 10,
    marginTop: '3%',
},
Txtservico_4: {
    flex: 1,
    marginTop: '3%',
},
Txtservico_5: {
    color: '#10C18D',
    marginLeft: '14%',
    marginTop: '10%',
    fontSize: 20,
    fontWeight: '600',
},
solcimputes3: {
    flex: 1,
    alignItems:'center',
    justifyContent: 'center',
    width:'70%',
    height:'80%',
    marginLeft: '15%',
},
inputservico3: {
    backgroundColor:'#E1E1E1',
    width:'100%',
    marginBottom: 15,
    color: '#222',
    fontSize: 15,
    borderRadius: 13,
    padding: 10,
    marginTop: '3%',
},
Txtservico_6: {
    flex: 1,
    marginTop: '20%',
},
Txtservico_7:{
    color: '#000',
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '400',
},
checkbox: {
    marginRight:'2%',
},
Termos:{
    flexDirection:'row',
    marginHorizontal:'16%',
    marginRight:'10%',
    marginTop:'7%',
},

BtnConfirmar: {
    backgroundColor: '#10C18D',
    width: 150,
    paddingVertical: 5,
    justifyContent: "center",
    alignItems: 'center',
    marginTop:'10%',
    marginLeft: '50%',
    borderRadius: 100,
    marginBottom:'8%',

},
BtnConfirmarTxt: {
    textAlign: 'center',
    color: 'white',
    fontSize: 20,
    fontWeight: '500',
    paddingLeft: 10,
    paddingRight: 10,
},

//----------------------------DIVULGAR CARGA-------------------------------------------
txtcarga: {
    flex: 1,
    marginTop: '20%',
},
Txtcarga_1: {
    color: '#10C18D',
    textAlign: 'center',
    marginTop: '20%',
    fontSize: 30,
    fontWeight: '700',
},
cargacimputes: {
    flex: 1,
    alignItems:'center',
    justifyContent: 'center',
    width:'70%',
    height:'80%',
    marginLeft: '15%',
},
inputcarga: {
    backgroundColor:'#E1E1E1',
    width:'100%',
    marginBottom: 15,
    color: '#222',
    fontSize: 15,
    borderRadius: 13,
    padding: 10,
    marginTop: '3%',
},
txtcarga2: {
    flex: 1,
    marginTop: '20%',
},
Txtcarga_2: {
    color: '#10C18D',
    textAlign: 'center',
    marginTop: '20%',
    fontSize: 30,
    fontWeight: '700',
},
Txtcarga_3: {
    color: '#113164',
    textAlign: 'center',
    marginTop: '20%',
    fontSize: 20,
    fontWeight: '600',
},
solcarga2: {
    flex: 1,
    alignItems:'center',
    justifyContent: 'center',
    width:'70%',
    height:'80%',
    marginLeft: '15%',
},
inputcarga2: {
    backgroundColor:'#E1E1E1',
    width:'100%',
    marginBottom: 15,
    color: '#222',
    fontSize: 15,
    borderRadius: 13,
    padding: 10,
    marginTop: '3%',
},
Txtcarga_4: {
    flex: 1,
    marginTop: '20%',
},
Txtcarga_5: {
    color: '#10C18D',
    textAlign: 'center',
    marginTop: '20%',
    fontSize: 30,
    fontWeight: '700',
},
solcarga3: {
    flex: 1,
    alignItems:'center',
    justifyContent: 'center',
    width:'70%',
    height:'80%',
    marginLeft: '15%',
},
inputcarga3: {
    backgroundColor:'#E1E1E1',
    width:'100%',
    marginBottom: 15,
    color: '#222',
    fontSize: 15,
    borderRadius: 13,
    padding: 10,
    marginTop: '3%',
},
BtnDivulgar: {
    backgroundColor: '#10C18D',
    height:'12%',
    justifyContent: "flex-end",
    alignItems: 'flex-end',
    marginTop:'20%',
    borderRadius: 50,
    marginBottom:'8%',
},
BtnDivulgarTxt: {
    textAlign: 'center',
    color: 'white',
    fontSize: 22,
    fontWeight: '600',
    paddingLeft: 40,
    paddingRight: 40,
},

//---------------------------CARGAS DIVULGADAS------------------------------------
container: {
    flex: 1,
    padding: 10,
    backgroundColor: '#f4f4f4',
    alignItems:'center',
},
card: {
    backgroundColor: '#fff',
    width: '80%',
    borderRadius: 20,
    padding: 25,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
},
title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#163D89',
    marginBottom: 5,
},
subtitle: {
    fontSize: 17,
    color: '#777',
    marginBottom: 10,
},
description: {
    fontSize: 14,
    color: '#10C18D',
    fontWeight:'bold',
    marginBottom: 15,
},
infoContainer: {
    marginBottom: 10,
},
infoTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#10C18D',
},
infoText: {
    fontSize: 14,
    color: '#555',
},
button: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#e0f7fa',
    padding: 10,
    borderRadius: 8,
    marginTop: 10,
  },
buttonText: {
    fontSize: 14,
    color: '#00796b',
    fontWeight: 'bold',
  },
dateText: {
    fontSize: 14,
    color: '#00796b',
  },
})